name: Test-Arm64

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
        repository: redis/redis
        path: redis
    - name: Prepare for cross-compilation
      run: |
          sudo dpkg --add-architecture arm64
          sudo sed -i 's/^deb /deb [arch=amd64] /g' /etc/apt/sources.list
          cat <<_END_ | sudo tee /etc/apt/sources.list.d/crosscompile.list
          deb [arch=arm64] http://ports.ubuntu.com $(lsb_release -cs) main universe
          deb [arch=arm64] http://ports.ubuntu.com $(lsb_release -cs)-updates main universe
          _END_
    - name: Setup Snapcraft
      run: |
          sudo snap install snapcraft --classic
          snapcraft --target-arch amd64
          snapcraft --target-arch arm64 --destructive-mode --enable-experimental-target-arch
      env:
        SNAPCRAFT_BUILD_ENVIRONMENT: host
